CREATE TABLE change(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE deepthoughts(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE thinking(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE world(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE abilities(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE choices(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE inspirational(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE life(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE live(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE miracle(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE miracles(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE aliteracy(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE books(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE classic(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE humor(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE beyourself(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE adulthood(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE success(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE VALUEZ(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE love(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE edison(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE failure(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE paraphrased(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE misattributedeleanorroosevelt(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE obvious(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE simile(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE friends(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE heartbreak(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE sisters(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE courage(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE simplicity(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE understand(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE fantasy(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE navigation(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE activism(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE apathy(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE hate(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE indifference(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE opposite(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE philosophy(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE friendship(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE lackoffriendship(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE lackoflove(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE marriage(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE unhappymarriage(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE contentment(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE fate(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE misattributedjohnlennon(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE planning(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE plans(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE poetry(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE happiness(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE attributednosource(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE religion(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE comedy(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE yourself(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE children(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE fairytales(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE imagination(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE music(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE learning(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE READZing(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE seuss(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE dumbledore(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE misattributedtomotherteresa(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE death(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE chocolate(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE food(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE misattributedtocslewis(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE knowledge(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE understanding(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE wisdom(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE library(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE READZ(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE READZers(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE READZingbooks(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE tea(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE girls(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE hope(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE attributed(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE fear(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE inspiration(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE thought(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE misattributedtoeinstein(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE drug(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE romance(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE novelistquotes(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE alcohol(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE thehungergames(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE bilbo(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE journey(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE lost(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE quest(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE travel(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE wander(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE livedeathlove(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE good(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE writing(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE regrets(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE education(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE troubles(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE openmind(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE authors(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE literature(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE insanity(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE lies(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE lying(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE selfindulgence(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE truth(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE beatles(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE connection(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE dreamers(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE dreaming(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE dreams(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE peace(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE sinister(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE mistakes(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE romantic(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE women(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE integrity(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE elizabethbennet(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE janeausten(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE age(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE growingup(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE god(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE misattributedmarktwain(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE christianity(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE faith(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE sun(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE adventure(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE betterlifeempathy(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE difficult(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE grownups(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE write(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE writers(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
CREATE TABLE mind(id INTEGER PRIMARY KEY, author TEXT NOT NULL, quote TEXT ); 
INSERT INTO change VALUES (0 , "Albert Einstein" , "The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking." ); 
INSERT INTO deepthoughts VALUES (0 , "Albert Einstein" , "The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking." ); 
INSERT INTO thinking VALUES (0 , "Albert Einstein" , "The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking." ); 
INSERT INTO thinking VALUES (5602 , "Terry Pratchett" , "The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it." ); 
INSERT INTO world VALUES (0 , "Albert Einstein" , "The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking." ); 
INSERT INTO abilities VALUES (1 , "J.K. Rowling" , "It is our choices, Harry, that show what we truly are, far more than our abilities." ); 
INSERT INTO choices VALUES (1 , "J.K. Rowling" , "It is our choices, Harry, that show what we truly are, far more than our abilities." ); 
INSERT INTO inspirational VALUES (2 , "Albert Einstein" , "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle." ); 
INSERT INTO inspirational VALUES (4 , "Marilyn Monroe" , "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring." ); 
INSERT INTO inspirational VALUES (7 , "Thomas A. Edison" , "I have not failed. I've just found 10,000 ways that won't work." ); 
INSERT INTO inspirational VALUES (800 , "Marilyn Monroe" , "This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about." ); 
INSERT INTO inspirational VALUES (806 , "Elie Wiesel" , "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference." ); 
INSERT INTO inspirational VALUES (2404 , "J.K. Rowling" , "To the well-organized mind, death is but the next great adventure." ); 
INSERT INTO inspirational VALUES (2409 , "George Eliot" , "It is never too late to be what you might have been." ); 
INSERT INTO inspirational VALUES (3201 , "C.S. Lewis" , "You can never get a cup of tea large enough or a book long enough to suit me." ); 
INSERT INTO inspirational VALUES (3207 , "Martin Luther King Jr." , "Only in the darkness can you see the stars." ); 
INSERT INTO inspirational VALUES (4008 , "Helen Keller" , "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us." ); 
INSERT INTO inspirational VALUES (4009 , "George Bernard Shaw" , "Life isn't about finding yourself. Life is about creating yourself." ); 
INSERT INTO inspirational VALUES (5606 , "John Lennon" , "You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one." ); 
INSERT INTO inspirational VALUES (7208 , "Dr. Seuss" , "A person's a person, no matter how small." ); 
INSERT INTO life VALUES (2 , "Albert Einstein" , "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle." ); 
INSERT INTO life VALUES (6 , "André Gide" , "It is better to be hated for what you are than to be loved for what you are not." ); 
INSERT INTO life VALUES (800 , "Marilyn Monroe" , "This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about." ); 
INSERT INTO life VALUES (805 , "Douglas Adams" , "I may not have gone where I intended to go, but I think I have ended up where I needed to be." ); 
INSERT INTO life VALUES (808 , "Mark Twain" , "Good friends, good books, and a sleepy conscience: this is the ideal life." ); 
INSERT INTO life VALUES (809 , "Allen Saunders" , "Life is what happens to us while we are making other plans." ); 
INSERT INTO life VALUES (1605 , "Dr. Seuss" , "Today you are You, that is truer than true. There is no one alive who is Youer than You." ); 
INSERT INTO life VALUES (3204 , "Albert Einstein" , "Life is like riding a bicycle. To keep your balance, you must keep moving." ); 
INSERT INTO life VALUES (4009 , "George Bernard Shaw" , "Life isn't about finding yourself. Life is about creating yourself." ); 
INSERT INTO life VALUES (4807 , "Ralph Waldo Emerson" , "Finish each day and be done with it. You have done what you could. Some blunders and absurdities no doubt crept in; forget them as soon as you can. Tomorrow is a new day. You shall begin it serenely and with too high a spirit to be encumbered with your old nonsense." ); 
INSERT INTO life VALUES (6407 , "Mark Twain" , "The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time." ); 
INSERT INTO life VALUES (7201 , "Jimi Hendrix" , "I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to." ); 
INSERT INTO life VALUES (7204 , "Khaled Hosseini" , "But better to get hurt by the truth than comforted with a lie." ); 
INSERT INTO live VALUES (2 , "Albert Einstein" , "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle." ); 
INSERT INTO miracle VALUES (2 , "Albert Einstein" , "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle." ); 
INSERT INTO miracles VALUES (2 , "Albert Einstein" , "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle." ); 
INSERT INTO aliteracy VALUES (3 , "Jane Austen" , "The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid." ); 
INSERT INTO books VALUES (3 , "Jane Austen" , "The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid." ); 
INSERT INTO books VALUES (808 , "Mark Twain" , "Good friends, good books, and a sleepy conscience: this is the ideal life." ); 
INSERT INTO books VALUES (2408 , "Jorge Luis Borges" , "I have always imagined that Paradise will be a kind of library." ); 
INSERT INTO books VALUES (3201 , "C.S. Lewis" , "You can never get a cup of tea large enough or a book long enough to suit me." ); 
INSERT INTO books VALUES (4004 , "Haruki Murakami" , "If you only read the books that everyone else is reading, you can only think what everyone else is thinking." ); 
INSERT INTO books VALUES (4007 , "Ernest Hemingway" , "There is no friend as loyal as a book." ); 
INSERT INTO books VALUES (5604 , "J.D. Salinger" , "What really knocks me out is a book that, when you're all done reading it, you wish the author that wrote it was a terrific friend of yours and you could call him up on the phone whenever you felt like it. That doesn't happen much, though." ); 
INSERT INTO books VALUES (5609 , "Mark Twain" , "′Classic′ - a book which people praise and don't read." ); 
INSERT INTO books VALUES (6403 , "Jane Austen" , "I declare after all there is no enjoyment like reading! How much sooner one tires of any thing than of a book! -- When I have a house of my own, I shall be miserable if I have not an excellent library." ); 
INSERT INTO books VALUES (7206 , "Madeleine L'Engle" , "You have to write the book that wants to be written. And if the book will be too difficult for grown-ups, then you write it for children." ); 
INSERT INTO books VALUES (7209 , "George R.R. Martin" , "... a mind needs books as a sword needs a whetstone, if it is to keep its edge." ); 
INSERT INTO classic VALUES (3 , "Jane Austen" , "The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid." ); 
INSERT INTO classic VALUES (5609 , "Mark Twain" , "′Classic′ - a book which people praise and don't read." ); 
INSERT INTO humor VALUES (3 , "Jane Austen" , "The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid." ); 
INSERT INTO humor VALUES (9 , "Steve Martin" , "A day without sunshine is like, you know, night." ); 
INSERT INTO humor VALUES (1603 , "Garrison Keillor" , "Anyone who thinks sitting in church can make you a Christian must also think that sitting in a garage can make you a car." ); 
INSERT INTO humor VALUES (1604 , "Jim Henson" , "Beauty is in the eye of the beholder and it may be necessary from time to time to give a stupid or misinformed beholder a black eye." ); 
INSERT INTO humor VALUES (2405 , "Charles M. Schulz" , "All you need is love. But a little chocolate now and then doesn't hurt." ); 
INSERT INTO humor VALUES (4802 , "Suzanne Collins" , "Remember, we're madly in love, so it's all right to kiss me anytime you feel like it." ); 
INSERT INTO humor VALUES (5601 , "Charles Bukowski" , "Some people never go crazy. What truly horrible lives they must lead." ); 
INSERT INTO humor VALUES (5602 , "Terry Pratchett" , "The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it." ); 
INSERT INTO humor VALUES (5603 , "Dr. Seuss" , "Think left and think right and think low and think high. Oh, the thinks you can think up if only you try!" ); 
INSERT INTO humor VALUES (5605 , "George Carlin" , "The reason I talk to myself is because I’m the only one whose answers I accept." ); 
INSERT INTO humor VALUES (5607 , "W.C. Fields" , "I am free of all prejudice. I hate everyone equally. " ); 
INSERT INTO humor VALUES (6401 , "Jane Austen" , "A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment." ); 
INSERT INTO beyourself VALUES (4 , "Marilyn Monroe" , "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring." ); 
INSERT INTO adulthood VALUES (5 , "Albert Einstein" , "Try not to become a man of success. Rather become a man of value." ); 
INSERT INTO success VALUES (5 , "Albert Einstein" , "Try not to become a man of success. Rather become a man of value." ); 
INSERT INTO VALUEZ VALUES (5 , "Albert Einstein" , "Try not to become a man of success. Rather become a man of value." ); 
INSERT INTO love VALUES (6 , "André Gide" , "It is better to be hated for what you are than to be loved for what you are not." ); 
INSERT INTO love VALUES (800 , "Marilyn Monroe" , "This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about." ); 
INSERT INTO love VALUES (803 , "Bob Marley" , "You may not be her first, her last, or her only. She loved before she may love again. But if she loves you now, what else matters? She's not perfect—you aren't either, and the two of you may never be perfect together but if she can make you laugh, cause you to think twice, and admit to being human and making mistakes, hold onto her and give her the most you can. She may not be thinking about you every second of the day, but she will give you a part of her that she knows you can break—her heart. So don't hurt her, don't change her, don't analyze and don't expect more than she can give. Smile when she makes you happy, let her know when she makes you mad, and miss her when she's not there." ); 
INSERT INTO love VALUES (806 , "Elie Wiesel" , "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference." ); 
INSERT INTO love VALUES (807 , "Friedrich Nietzsche" , "It is not a lack of love, but a lack of friendship that makes unhappy marriages." ); 
INSERT INTO love VALUES (1600 , "Pablo Neruda" , "I love you without knowing how, or when, or from where. I love you simply, without problems or pride: I love you in this way because I do not know any other way of loving but this, in which there is no I or you, so intimate that your hand upon my chest is my hand, so intimate that when I fall asleep your eyes close." ); 
INSERT INTO love VALUES (3203 , "Marilyn Monroe" , "If you can make a woman laugh, you can make her do anything." ); 
INSERT INTO love VALUES (3205 , "Marilyn Monroe" , "The real lover is the man who can thrill you by kissing your forehead or smiling into your eyes or just staring into space." ); 
INSERT INTO love VALUES (3209 , "James Baldwin" , "Love does not begin and end the way we seem to think it does. Love is a battle, love is a war; love is a growing up." ); 
INSERT INTO love VALUES (4000 , "Jane Austen" , "There is nothing I would not do for those who are really my friends. I have no notion of loving people by halves, it is not my nature." ); 
INSERT INTO love VALUES (4803 , "C.S. Lewis" , "To love at all is to be vulnerable. Love anything and your heart will be wrung and possibly broken. If you want to make sure of keeping it intact you must give it to no one, not even an animal. Wrap it carefully round with hobbies and little luxuries; avoid all entanglements. Lock it up safe in the casket or coffin of your selfishness. But in that casket, safe, dark, motionless, airless, it will change. It will not be broken; it will become unbreakable, impenetrable, irredeemable. To love is to be vulnerable." ); 
INSERT INTO love VALUES (5600 , "Alfred Tennyson" , "If I had a flower for every time I thought of you...I could walk through my garden forever." ); 
INSERT INTO love VALUES (6401 , "Jane Austen" , "A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment." ); 
INSERT INTO love VALUES (7202 , "J.M. Barrie" , "To die will be an awfully big adventure." ); 
INSERT INTO edison VALUES (7 , "Thomas A. Edison" , "I have not failed. I've just found 10,000 ways that won't work." ); 
INSERT INTO failure VALUES (7 , "Thomas A. Edison" , "I have not failed. I've just found 10,000 ways that won't work." ); 
INSERT INTO paraphrased VALUES (7 , "Thomas A. Edison" , "I have not failed. I've just found 10,000 ways that won't work." ); 
INSERT INTO paraphrased VALUES (2403 , "Mother Teresa" , "Not all of us can do great things. But we can do small things with great love." ); 
INSERT INTO misattributedeleanorroosevelt VALUES (8 , "Eleanor Roosevelt" , "A woman is like a tea bag; you never know how strong it is until it's in hot water." ); 
INSERT INTO obvious VALUES (9 , "Steve Martin" , "A day without sunshine is like, you know, night." ); 
INSERT INTO simile VALUES (9 , "Steve Martin" , "A day without sunshine is like, you know, night." ); 
INSERT INTO simile VALUES (3204 , "Albert Einstein" , "Life is like riding a bicycle. To keep your balance, you must keep moving." ); 
INSERT INTO simile VALUES (4006 , "Stephenie Meyer" , "He's like a drug for you, Bella." ); 
INSERT INTO friends VALUES (800 , "Marilyn Monroe" , "This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about." ); 
INSERT INTO friends VALUES (801 , "J.K. Rowling" , "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends." ); 
INSERT INTO friends VALUES (808 , "Mark Twain" , "Good friends, good books, and a sleepy conscience: this is the ideal life." ); 
INSERT INTO friends VALUES (4007 , "Ernest Hemingway" , "There is no friend as loyal as a book." ); 
INSERT INTO heartbreak VALUES (800 , "Marilyn Monroe" , "This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about." ); 
INSERT INTO sisters VALUES (800 , "Marilyn Monroe" , "This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about." ); 
INSERT INTO courage VALUES (801 , "J.K. Rowling" , "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends." ); 
INSERT INTO courage VALUES (7203 , "E.E. Cummings" , "It takes courage to grow up and become who you really are." ); 
INSERT INTO simplicity VALUES (802 , "Albert Einstein" , "If you can't explain it to a six year old, you don't understand it yourself." ); 
INSERT INTO understand VALUES (802 , "Albert Einstein" , "If you can't explain it to a six year old, you don't understand it yourself." ); 
INSERT INTO fantasy VALUES (804 , "Dr. Seuss" , "I like nonsense, it wakes up the brain cells. Fantasy is a necessary ingredient in living." ); 
INSERT INTO navigation VALUES (805 , "Douglas Adams" , "I may not have gone where I intended to go, but I think I have ended up where I needed to be." ); 
INSERT INTO activism VALUES (806 , "Elie Wiesel" , "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference." ); 
INSERT INTO apathy VALUES (806 , "Elie Wiesel" , "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference." ); 
INSERT INTO hate VALUES (806 , "Elie Wiesel" , "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference." ); 
INSERT INTO indifference VALUES (806 , "Elie Wiesel" , "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference." ); 
INSERT INTO opposite VALUES (806 , "Elie Wiesel" , "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference." ); 
INSERT INTO philosophy VALUES (806 , "Elie Wiesel" , "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference." ); 
INSERT INTO philosophy VALUES (5603 , "Dr. Seuss" , "Think left and think right and think low and think high. Oh, the thinks you can think up if only you try!" ); 
INSERT INTO friendship VALUES (807 , "Friedrich Nietzsche" , "It is not a lack of love, but a lack of friendship that makes unhappy marriages." ); 
INSERT INTO friendship VALUES (808 , "Mark Twain" , "Good friends, good books, and a sleepy conscience: this is the ideal life." ); 
INSERT INTO friendship VALUES (2402 , "Bob Marley" , "The truth is, everyone is going to hurt you. You just got to find the ones worth suffering for." ); 
INSERT INTO friendship VALUES (4000 , "Jane Austen" , "There is nothing I would not do for those who are really my friends. I have no notion of loving people by halves, it is not my nature." ); 
INSERT INTO friendship VALUES (5600 , "Alfred Tennyson" , "If I had a flower for every time I thought of you...I could walk through my garden forever." ); 
INSERT INTO lackoffriendship VALUES (807 , "Friedrich Nietzsche" , "It is not a lack of love, but a lack of friendship that makes unhappy marriages." ); 
INSERT INTO lackoflove VALUES (807 , "Friedrich Nietzsche" , "It is not a lack of love, but a lack of friendship that makes unhappy marriages." ); 
INSERT INTO marriage VALUES (807 , "Friedrich Nietzsche" , "It is not a lack of love, but a lack of friendship that makes unhappy marriages." ); 
INSERT INTO unhappymarriage VALUES (807 , "Friedrich Nietzsche" , "It is not a lack of love, but a lack of friendship that makes unhappy marriages." ); 
INSERT INTO contentment VALUES (808 , "Mark Twain" , "Good friends, good books, and a sleepy conscience: this is the ideal life." ); 
INSERT INTO fate VALUES (809 , "Allen Saunders" , "Life is what happens to us while we are making other plans." ); 
INSERT INTO misattributedjohnlennon VALUES (809 , "Allen Saunders" , "Life is what happens to us while we are making other plans." ); 
INSERT INTO planning VALUES (809 , "Allen Saunders" , "Life is what happens to us while we are making other plans." ); 
INSERT INTO plans VALUES (809 , "Allen Saunders" , "Life is what happens to us while we are making other plans." ); 
INSERT INTO poetry VALUES (1600 , "Pablo Neruda" , "I love you without knowing how, or when, or from where. I love you simply, without problems or pride: I love you in this way because I do not know any other way of loving but this, in which there is no I or you, so intimate that your hand upon my chest is my hand, so intimate that when I fall asleep your eyes close." ); 
INSERT INTO happiness VALUES (1601 , "Ralph Waldo Emerson" , "For every minute you are angry you lose sixty seconds of happiness." ); 
INSERT INTO attributednosource VALUES (1602 , "Mother Teresa" , "If you judge people, you have no time to love them." ); 
INSERT INTO attributednosource VALUES (3206 , "Marilyn Monroe" , "A wise girl kisses but doesn't love, listens but doesn't believe, and leaves before she is left." ); 
INSERT INTO attributednosource VALUES (4002 , "Marilyn Monroe" , "I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love." ); 
INSERT INTO religion VALUES (1603 , "Garrison Keillor" , "Anyone who thinks sitting in church can make you a Christian must also think that sitting in a garage can make you a car." ); 
INSERT INTO religion VALUES (6409 , "C.S. Lewis" , "I believe in Christianity as I believe that the sun has risen: not only because I see it, but because by it I see everything else." ); 
INSERT INTO comedy VALUES (1605 , "Dr. Seuss" , "Today you are You, that is truer than true. There is no one alive who is Youer than You." ); 
INSERT INTO yourself VALUES (1605 , "Dr. Seuss" , "Today you are You, that is truer than true. There is no one alive who is Youer than You." ); 
INSERT INTO yourself VALUES (4009 , "George Bernard Shaw" , "Life isn't about finding yourself. Life is about creating yourself." ); 
INSERT INTO children VALUES (1606 , "Albert Einstein" , "If you want your children to be intelligent, read them fairy tales. If you want them to be more intelligent, read them more fairy tales." ); 
INSERT INTO children VALUES (7206 , "Madeleine L'Engle" , "You have to write the book that wants to be written. And if the book will be too difficult for grown-ups, then you write it for children." ); 
INSERT INTO fairytales VALUES (1606 , "Albert Einstein" , "If you want your children to be intelligent, read them fairy tales. If you want them to be more intelligent, read them more fairy tales." ); 
INSERT INTO fairytales VALUES (6405 , "C.S. Lewis" , "Some day you will be old enough to start reading fairy tales again." ); 
INSERT INTO imagination VALUES (1608 , "Albert Einstein" , "Logic will get you from A to Z; imagination will get you everywhere." ); 
INSERT INTO music VALUES (1609 , "Bob Marley" , "One good thing about music, when it hits you, you feel no pain." ); 
INSERT INTO music VALUES (4003 , "Albert Einstein" , "If I were not a physicist, I would probably be a musician. I often think in music. I live my daydreams in music. I see my life in terms of music." ); 
INSERT INTO learning VALUES (2400 , "Dr. Seuss" , "The more that you read, the more things you will know. The more that you learn, the more places you'll go." ); 
INSERT INTO learning VALUES (2407 , "Albert Einstein" , "Any fool can know. The point is to understand." ); 
INSERT INTO READZing VALUES (2400 , "Dr. Seuss" , "The more that you read, the more things you will know. The more that you learn, the more places you'll go." ); 
INSERT INTO READZing VALUES (2406 , "William Nicholson" , "We read to know we're not alone." ); 
INSERT INTO READZing VALUES (3200 , "George R.R. Martin" , "A reader lives a thousand lives before he dies, said Jojen. The man who never reads lives only one." ); 
INSERT INTO READZing VALUES (3201 , "C.S. Lewis" , "You can never get a cup of tea large enough or a book long enough to suit me." ); 
INSERT INTO READZing VALUES (5604 , "J.D. Salinger" , "What really knocks me out is a book that, when you're all done reading it, you wish the author that wrote it was a terrific friend of yours and you could call him up on the phone whenever you felt like it. That doesn't happen much, though." ); 
INSERT INTO READZing VALUES (5609 , "Mark Twain" , "′Classic′ - a book which people praise and don't read." ); 
INSERT INTO READZing VALUES (6403 , "Jane Austen" , "I declare after all there is no enjoyment like reading! How much sooner one tires of any thing than of a book! -- When I have a house of my own, I shall be miserable if I have not an excellent library." ); 
INSERT INTO seuss VALUES (2400 , "Dr. Seuss" , "The more that you read, the more things you will know. The more that you learn, the more places you'll go." ); 
INSERT INTO dumbledore VALUES (2401 , "J.K. Rowling" , "Of course it is happening inside your head, Harry, but why on earth should that mean that it is not real?" ); 
INSERT INTO dumbledore VALUES (3208 , "J.K. Rowling" , "It matters not what someone is born, but what they grow to be." ); 
INSERT INTO misattributedtomotherteresa VALUES (2403 , "Mother Teresa" , "Not all of us can do great things. But we can do small things with great love." ); 
INSERT INTO death VALUES (2404 , "J.K. Rowling" , "To the well-organized mind, death is but the next great adventure." ); 
INSERT INTO death VALUES (6407 , "Mark Twain" , "The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time." ); 
INSERT INTO death VALUES (7201 , "Jimi Hendrix" , "I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to." ); 
INSERT INTO chocolate VALUES (2405 , "Charles M. Schulz" , "All you need is love. But a little chocolate now and then doesn't hurt." ); 
INSERT INTO food VALUES (2405 , "Charles M. Schulz" , "All you need is love. But a little chocolate now and then doesn't hurt." ); 
INSERT INTO misattributedtocslewis VALUES (2406 , "William Nicholson" , "We read to know we're not alone." ); 
INSERT INTO knowledge VALUES (2407 , "Albert Einstein" , "Any fool can know. The point is to understand." ); 
INSERT INTO understanding VALUES (2407 , "Albert Einstein" , "Any fool can know. The point is to understand." ); 
INSERT INTO wisdom VALUES (2407 , "Albert Einstein" , "Any fool can know. The point is to understand." ); 
INSERT INTO library VALUES (2408 , "Jorge Luis Borges" , "I have always imagined that Paradise will be a kind of library." ); 
INSERT INTO library VALUES (6403 , "Jane Austen" , "I declare after all there is no enjoyment like reading! How much sooner one tires of any thing than of a book! -- When I have a house of my own, I shall be miserable if I have not an excellent library." ); 
INSERT INTO READZ VALUES (3200 , "George R.R. Martin" , "A reader lives a thousand lives before he dies, said Jojen. The man who never reads lives only one." ); 
INSERT INTO READZers VALUES (3200 , "George R.R. Martin" , "A reader lives a thousand lives before he dies, said Jojen. The man who never reads lives only one." ); 
INSERT INTO READZingbooks VALUES (3200 , "George R.R. Martin" , "A reader lives a thousand lives before he dies, said Jojen. The man who never reads lives only one." ); 
INSERT INTO tea VALUES (3201 , "C.S. Lewis" , "You can never get a cup of tea large enough or a book long enough to suit me." ); 
INSERT INTO girls VALUES (3203 , "Marilyn Monroe" , "If you can make a woman laugh, you can make her do anything." ); 
INSERT INTO hope VALUES (3207 , "Martin Luther King Jr." , "Only in the darkness can you see the stars." ); 
INSERT INTO hope VALUES (5606 , "John Lennon" , "You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one." ); 
INSERT INTO attributed VALUES (4001 , "Eleanor Roosevelt" , "Do one thing every day that scares you." ); 
INSERT INTO fear VALUES (4001 , "Eleanor Roosevelt" , "Do one thing every day that scares you." ); 
INSERT INTO inspiration VALUES (4001 , "Eleanor Roosevelt" , "Do one thing every day that scares you." ); 
INSERT INTO thought VALUES (4004 , "Haruki Murakami" , "If you only read the books that everyone else is reading, you can only think what everyone else is thinking." ); 
INSERT INTO misattributedtoeinstein VALUES (4005 , "Alexandre Dumas fils" , "The difference between genius and stupidity is: genius has its limits." ); 
INSERT INTO drug VALUES (4006 , "Stephenie Meyer" , "He's like a drug for you, Bella." ); 
INSERT INTO romance VALUES (4006 , "Stephenie Meyer" , "He's like a drug for you, Bella." ); 
INSERT INTO novelistquotes VALUES (4007 , "Ernest Hemingway" , "There is no friend as loyal as a book." ); 
INSERT INTO alcohol VALUES (4800 , "Charles Bukowski" , "That's the problem with drinking, I thought, as I poured myself a drink. If something bad happens you drink in an attempt to forget; if something good happens you drink in order to celebrate; and if nothing happens you drink to make something happen." ); 
INSERT INTO thehungergames VALUES (4801 , "Suzanne Collins" , "You don’t forget the face of the person who was your last hope." ); 
INSERT INTO bilbo VALUES (4804 , "J.R.R. Tolkien" , "Not all those who wander are lost." ); 
INSERT INTO journey VALUES (4804 , "J.R.R. Tolkien" , "Not all those who wander are lost." ); 
INSERT INTO lost VALUES (4804 , "J.R.R. Tolkien" , "Not all those who wander are lost." ); 
INSERT INTO quest VALUES (4804 , "J.R.R. Tolkien" , "Not all those who wander are lost." ); 
INSERT INTO travel VALUES (4804 , "J.R.R. Tolkien" , "Not all those who wander are lost." ); 
INSERT INTO wander VALUES (4804 , "J.R.R. Tolkien" , "Not all those who wander are lost." ); 
INSERT INTO livedeathlove VALUES (4805 , "J.K. Rowling" , "Do not pity the dead, Harry. Pity the living, and, above all those who live without love." ); 
INSERT INTO good VALUES (4806 , "Ernest Hemingway" , "There is nothing to writing. All you do is sit down at a typewriter and bleed." ); 
INSERT INTO writing VALUES (4806 , "Ernest Hemingway" , "There is nothing to writing. All you do is sit down at a typewriter and bleed." ); 
INSERT INTO writing VALUES (5604 , "J.D. Salinger" , "What really knocks me out is a book that, when you're all done reading it, you wish the author that wrote it was a terrific friend of yours and you could call him up on the phone whenever you felt like it. That doesn't happen much, though." ); 
INSERT INTO writing VALUES (7206 , "Madeleine L'Engle" , "You have to write the book that wants to be written. And if the book will be too difficult for grown-ups, then you write it for children." ); 
INSERT INTO regrets VALUES (4807 , "Ralph Waldo Emerson" , "Finish each day and be done with it. You have done what you could. Some blunders and absurdities no doubt crept in; forget them as soon as you can. Tomorrow is a new day. You shall begin it serenely and with too high a spirit to be encumbered with your old nonsense." ); 
INSERT INTO education VALUES (4808 , "Mark Twain" , "I have never let my schooling interfere with my education." ); 
INSERT INTO troubles VALUES (4809 , "Dr. Seuss" , "I have heard there are troubles of more than one kind. Some come from ahead and some come from behind. But I've bought a big bat. I'm all ready you see. Now my troubles are going to have troubles with me!" ); 
INSERT INTO openmind VALUES (5602 , "Terry Pratchett" , "The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it." ); 
INSERT INTO authors VALUES (5604 , "J.D. Salinger" , "What really knocks me out is a book that, when you're all done reading it, you wish the author that wrote it was a terrific friend of yours and you could call him up on the phone whenever you felt like it. That doesn't happen much, though." ); 
INSERT INTO literature VALUES (5604 , "J.D. Salinger" , "What really knocks me out is a book that, when you're all done reading it, you wish the author that wrote it was a terrific friend of yours and you could call him up on the phone whenever you felt like it. That doesn't happen much, though." ); 
INSERT INTO insanity VALUES (5605 , "George Carlin" , "The reason I talk to myself is because I’m the only one whose answers I accept." ); 
INSERT INTO lies VALUES (5605 , "George Carlin" , "The reason I talk to myself is because I’m the only one whose answers I accept." ); 
INSERT INTO lying VALUES (5605 , "George Carlin" , "The reason I talk to myself is because I’m the only one whose answers I accept." ); 
INSERT INTO selfindulgence VALUES (5605 , "George Carlin" , "The reason I talk to myself is because I’m the only one whose answers I accept." ); 
INSERT INTO truth VALUES (5605 , "George Carlin" , "The reason I talk to myself is because I’m the only one whose answers I accept." ); 
INSERT INTO truth VALUES (6408 , "Mark Twain" , "A lie can travel half way around the world while the truth is putting on its shoes." ); 
INSERT INTO truth VALUES (7200 , "J.K. Rowling" , "The truth." Dumbledore sighed. "It is a beautiful and terrible thing, and should therefore be treated with great caution." ); 
INSERT INTO truth VALUES (7207 , "Mark Twain" , "Never tell the truth to people who are not worthy of it." ); 
INSERT INTO beatles VALUES (5606 , "John Lennon" , "You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one." ); 
INSERT INTO connection VALUES (5606 , "John Lennon" , "You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one." ); 
INSERT INTO dreamers VALUES (5606 , "John Lennon" , "You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one." ); 
INSERT INTO dreaming VALUES (5606 , "John Lennon" , "You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one." ); 
INSERT INTO dreams VALUES (5606 , "John Lennon" , "You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one." ); 
INSERT INTO peace VALUES (5606 , "John Lennon" , "You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one." ); 
INSERT INTO sinister VALUES (5607 , "W.C. Fields" , "I am free of all prejudice. I hate everyone equally. " ); 
INSERT INTO mistakes VALUES (6400 , "Albert Einstein" , "Anyone who has never made a mistake has never tried anything new." ); 
INSERT INTO romantic VALUES (6401 , "Jane Austen" , "A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment." ); 
INSERT INTO women VALUES (6401 , "Jane Austen" , "A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment." ); 
INSERT INTO integrity VALUES (6402 , "J.K. Rowling" , "Remember, if the time should come when you have to make a choice between what is right and what is easy, remember what happened to a boy who was good, and kind, and brave, because he strayed across the path of Lord Voldemort. Remember Cedric Diggory." ); 
INSERT INTO elizabethbennet VALUES (6404 , "Jane Austen" , "There are few people whom I really love, and still fewer of whom I think well. The more I see of the world, the more am I dissatisfied with it; and every day confirms my belief of the inconsistency of all human characters, and of the little dependence that can be placed on the appearance of merit or sense." ); 
INSERT INTO janeausten VALUES (6404 , "Jane Austen" , "There are few people whom I really love, and still fewer of whom I think well. The more I see of the world, the more am I dissatisfied with it; and every day confirms my belief of the inconsistency of all human characters, and of the little dependence that can be placed on the appearance of merit or sense." ); 
INSERT INTO age VALUES (6405 , "C.S. Lewis" , "Some day you will be old enough to start reading fairy tales again." ); 
INSERT INTO growingup VALUES (6405 , "C.S. Lewis" , "Some day you will be old enough to start reading fairy tales again." ); 
INSERT INTO god VALUES (6406 , "C.S. Lewis" , "We are not necessarily doubting that God will do the best for us; we are wondering how painful the best will turn out to be." ); 
INSERT INTO misattributedmarktwain VALUES (6408 , "Mark Twain" , "A lie can travel half way around the world while the truth is putting on its shoes." ); 
INSERT INTO christianity VALUES (6409 , "C.S. Lewis" , "I believe in Christianity as I believe that the sun has risen: not only because I see it, but because by it I see everything else." ); 
INSERT INTO faith VALUES (6409 , "C.S. Lewis" , "I believe in Christianity as I believe that the sun has risen: not only because I see it, but because by it I see everything else." ); 
INSERT INTO sun VALUES (6409 , "C.S. Lewis" , "I believe in Christianity as I believe that the sun has risen: not only because I see it, but because by it I see everything else." ); 
INSERT INTO adventure VALUES (7202 , "J.M. Barrie" , "To die will be an awfully big adventure." ); 
INSERT INTO betterlifeempathy VALUES (7205 , "Harper Lee" , "You never really understand a person until you consider things from his point of view... Until you climb inside of his skin and walk around in it." ); 
INSERT INTO difficult VALUES (7206 , "Madeleine L'Engle" , "You have to write the book that wants to be written. And if the book will be too difficult for grown-ups, then you write it for children." ); 
INSERT INTO grownups VALUES (7206 , "Madeleine L'Engle" , "You have to write the book that wants to be written. And if the book will be too difficult for grown-ups, then you write it for children." ); 
INSERT INTO write VALUES (7206 , "Madeleine L'Engle" , "You have to write the book that wants to be written. And if the book will be too difficult for grown-ups, then you write it for children." ); 
INSERT INTO writers VALUES (7206 , "Madeleine L'Engle" , "You have to write the book that wants to be written. And if the book will be too difficult for grown-ups, then you write it for children." ); 
INSERT INTO mind VALUES (7209 , "George R.R. Martin" , "... a mind needs books as a sword needs a whetstone, if it is to keep its edge." ); 
