CREATE TABLE QUOTES (id INTEGER PRIMARY KEY, author TEXT NOT NULL, cat TEXT NOT NULL, quote TEXT); 
CREATE TABLE RATING (id INTEGER, rating INTEGER,FOREIGN KEY(id) REFERENCES QUOTES(id) ON DELETE CASCADE);
INSERT INTO QUOTES VALUES (0 , "Albert Einstein" ,  "change " ,  "The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking. " ); 
INSERT INTO RATING VALUES (0,4);
INSERT INTO QUOTES VALUES (1 , "Albert Einstein" ,  "deepthoughts " ,  "The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking. " ); 
INSERT INTO RATING VALUES (1,1);
INSERT INTO QUOTES VALUES (2 , "Albert Einstein" ,  "thinking " ,  "The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking. " ); 
INSERT INTO RATING VALUES (2,5);
INSERT INTO QUOTES VALUES (5605 , "Terry Pratchett" ,  "thinking " ,  "The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it. " ); 
INSERT INTO RATING VALUES (5605,3);
INSERT INTO QUOTES VALUES (3 , "Albert Einstein" ,  "world " ,  "The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking. " ); 
INSERT INTO RATING VALUES (3,10);
INSERT INTO QUOTES VALUES (4 , "J.K. Rowling" ,  "abilities " ,  "It is our choices, Harry, that show what we truly are, far more than our abilities. " ); 
INSERT INTO RATING VALUES (4,4);
INSERT INTO QUOTES VALUES (5 , "J.K. Rowling" ,  "choices " ,  "It is our choices, Harry, that show what we truly are, far more than our abilities. " ); 
INSERT INTO RATING VALUES (5,4);
INSERT INTO QUOTES VALUES (6 , "Albert Einstein" ,  "inspirational " ,  "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle. " ); 
INSERT INTO RATING VALUES (6,5);
INSERT INTO QUOTES VALUES (16 , "Marilyn Monroe" ,  "inspirational " ,  "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring. " ); 
INSERT INTO RATING VALUES (16,9);
INSERT INTO QUOTES VALUES (24 , "Thomas A. Edison" ,  "inspirational " ,  "I have not failed. I've just found 10,000 ways that won't work. " ); 
INSERT INTO RATING VALUES (24,10);
INSERT INTO QUOTES VALUES (802 , "Marilyn Monroe" ,  "inspirational " ,  "This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about. " ); 
INSERT INTO RATING VALUES (802,1);
INSERT INTO QUOTES VALUES (818 , "Elie Wiesel" ,  "inspirational " ,  "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference. " ); 
INSERT INTO RATING VALUES (818,2);
INSERT INTO QUOTES VALUES (2408 , "J.K. Rowling" ,  "inspirational " ,  "To the well-organized mind, death is but the next great adventure. " ); 
INSERT INTO RATING VALUES (2408,2);
INSERT INTO QUOTES VALUES (2420 , "George Eliot" ,  "inspirational " ,  "It is never too late to be what you might have been. " ); 
INSERT INTO RATING VALUES (2420,9);
INSERT INTO QUOTES VALUES (3205 , "C.S. Lewis" ,  "inspirational " ,  "You can never get a cup of tea large enough or a book long enough to suit me. " ); 
INSERT INTO RATING VALUES (3205,8);
INSERT INTO QUOTES VALUES (3215 , "Martin Luther King Jr." ,  "inspirational " ,  "Only in the darkness can you see the stars. " ); 
INSERT INTO RATING VALUES (3215,6);
INSERT INTO QUOTES VALUES (4016 , "Helen Keller" ,  "inspirational " ,  "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us. " ); 
INSERT INTO RATING VALUES (4016,7);
INSERT INTO QUOTES VALUES (4017 , "George Bernard Shaw" ,  "inspirational " ,  "Life isn't about finding yourself. Life is about creating yourself. " ); 
INSERT INTO RATING VALUES (4017,6);
INSERT INTO QUOTES VALUES (5625 , "John Lennon" ,  "inspirational " ,  "You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one. " ); 
INSERT INTO RATING VALUES (5625,2);
INSERT INTO QUOTES VALUES (7216 , "Dr. Seuss" ,  "inspirational " ,  "A person's a person, no matter how small. " ); 
INSERT INTO RATING VALUES (7216,7);
INSERT INTO QUOTES VALUES (7 , "Albert Einstein" ,  "life " ,  "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle. " ); 
INSERT INTO RATING VALUES (7,3);
INSERT INTO QUOTES VALUES (20 , "André Gide" ,  "life " ,  "It is better to be hated for what you are than to be loved for what you are not. " ); 
INSERT INTO RATING VALUES (20,5);
INSERT INTO QUOTES VALUES (803 , "Marilyn Monroe" ,  "life " ,  "This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about. " ); 
INSERT INTO RATING VALUES (803,3);
INSERT INTO QUOTES VALUES (812 , "Douglas Adams" ,  "life " ,  "I may not have gone where I intended to go, but I think I have ended up where I needed to be. " ); 
INSERT INTO RATING VALUES (812,0);
INSERT INTO QUOTES VALUES (832 , "Mark Twain" ,  "life " ,  "Good friends, good books, and a sleepy conscience: this is the ideal life. " ); 
INSERT INTO RATING VALUES (832,3);
INSERT INTO QUOTES VALUES (834 , "Allen Saunders" ,  "life " ,  "Life is what happens to us while we are making other plans. " ); 
INSERT INTO RATING VALUES (834,9);
INSERT INTO QUOTES VALUES (1608 , "Dr. Seuss" ,  "life " ,  "Today you are You, that is truer than true. There is no one alive who is Youer than You. " ); 
INSERT INTO RATING VALUES (1608,5);
INSERT INTO QUOTES VALUES (3210 , "Albert Einstein" ,  "life " ,  "Life is like riding a bicycle. To keep your balance, you must keep moving. " ); 
INSERT INTO RATING VALUES (3210,5);
INSERT INTO QUOTES VALUES (4018 , "George Bernard Shaw" ,  "life " ,  "Life isn't about finding yourself. Life is about creating yourself. " ); 
INSERT INTO RATING VALUES (4018,0);
INSERT INTO QUOTES VALUES (4813 , "Ralph Waldo Emerson" ,  "life " ,  "Finish each day and be done with it. You have done what you could. Some blunders and absurdities no doubt crept in; forget them as soon as you can. Tomorrow is a new day. You shall begin it serenely and with too high a spirit to be encumbered with your old nonsense. " ); 
INSERT INTO RATING VALUES (4813,6);
INSERT INTO QUOTES VALUES (6416 , "Mark Twain" ,  "life " ,  "The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time. " ); 
INSERT INTO RATING VALUES (6416,9);
INSERT INTO QUOTES VALUES (7202 , "Jimi Hendrix" ,  "life " ,  "I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to. " ); 
INSERT INTO RATING VALUES (7202,9);
INSERT INTO QUOTES VALUES (7206 , "Khaled Hosseini" ,  "life " ,  "But better to get hurt by the truth than comforted with a lie. " ); 
INSERT INTO RATING VALUES (7206,2);
INSERT INTO QUOTES VALUES (8 , "Albert Einstein" ,  "live " ,  "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle. " ); 
INSERT INTO RATING VALUES (8,6);
INSERT INTO QUOTES VALUES (9 , "Albert Einstein" ,  "miracle " ,  "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle. " ); 
INSERT INTO RATING VALUES (9,4);
INSERT INTO QUOTES VALUES (10 , "Albert Einstein" ,  "miracles " ,  "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle. " ); 
INSERT INTO RATING VALUES (10,1);
INSERT INTO QUOTES VALUES (11 , "Jane Austen" ,  "aliteracy " ,  "The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid. " ); 
INSERT INTO RATING VALUES (11,1);
INSERT INTO QUOTES VALUES (12 , "Jane Austen" ,  "books " ,  "The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid. " ); 
INSERT INTO RATING VALUES (12,5);
INSERT INTO QUOTES VALUES (828 , "Mark Twain" ,  "books " ,  "Good friends, good books, and a sleepy conscience: this is the ideal life. " ); 
INSERT INTO RATING VALUES (828,10);
INSERT INTO QUOTES VALUES (2418 , "Jorge Luis Borges" ,  "books " ,  "I have always imagined that Paradise will be a kind of library. " ); 
INSERT INTO RATING VALUES (2418,6);
INSERT INTO QUOTES VALUES (3204 , "C.S. Lewis" ,  "books " ,  "You can never get a cup of tea large enough or a book long enough to suit me. " ); 
INSERT INTO RATING VALUES (3204,10);
INSERT INTO QUOTES VALUES (4007 , "Haruki Murakami" ,  "books " ,  "If you only read the books that everyone else is reading, you can only think what everyone else is thinking. " ); 
INSERT INTO RATING VALUES (4007,7);
INSERT INTO QUOTES VALUES (4013 , "Ernest Hemingway" ,  "books " ,  "There is no friend as loyal as a book. " ); 
INSERT INTO RATING VALUES (4013,7);
INSERT INTO QUOTES VALUES (5609 , "J.D. Salinger" ,  "books " ,  "What really knocks me out is a book that, when you're all done reading it, you wish the author that wrote it was a terrific friend of yours and you could call him up on the phone whenever you felt like it. That doesn't happen much, though. " ); 
INSERT INTO RATING VALUES (5609,9);
INSERT INTO QUOTES VALUES (5629 , "Mark Twain" ,  "books " ,  "′Classic′ - a book which people praise and don't read. " ); 
INSERT INTO RATING VALUES (5629,9);
INSERT INTO QUOTES VALUES (6406 , "Jane Austen" ,  "books " ,  "I declare after all there is no enjoyment like reading! How much sooner one tires of any thing than of a book! -- When I have a house of my own, I shall be miserable if I have not an excellent library. " ); 
INSERT INTO RATING VALUES (6406,2);
INSERT INTO QUOTES VALUES (7208 , "Madeleine L'Engle" ,  "books " ,  "You have to write the book that wants to be written. And if the book will be too difficult for grown-ups, then you write it for children. " ); 
INSERT INTO RATING VALUES (7208,1);
INSERT INTO QUOTES VALUES (7217 , "George R.R. Martin" ,  "books " ,  "... a mind needs books as a sword needs a whetstone, if it is to keep its edge. " ); 
INSERT INTO RATING VALUES (7217,10);
INSERT INTO QUOTES VALUES (13 , "Jane Austen" ,  "classic " ,  "The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid. " ); 
INSERT INTO RATING VALUES (13,2);
INSERT INTO QUOTES VALUES (5630 , "Mark Twain" ,  "classic " ,  "′Classic′ - a book which people praise and don't read. " ); 
INSERT INTO RATING VALUES (5630,4);
INSERT INTO QUOTES VALUES (14 , "Jane Austen" ,  "humor " ,  "The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid. " ); 
INSERT INTO RATING VALUES (14,4);
INSERT INTO QUOTES VALUES (27 , "Steve Martin" ,  "humor " ,  "A day without sunshine is like, you know, night. " ); 
INSERT INTO RATING VALUES (27,1);
INSERT INTO QUOTES VALUES (1604 , "Garrison Keillor" ,  "humor " ,  "Anyone who thinks sitting in church can make you a Christian must also think that sitting in a garage can make you a car. " ); 
INSERT INTO RATING VALUES (1604,6);
INSERT INTO QUOTES VALUES (1606 , "Jim Henson" ,  "humor " ,  "Beauty is in the eye of the beholder and it may be necessary from time to time to give a stupid or misinformed beholder a black eye. " ); 
INSERT INTO RATING VALUES (1606,0);
INSERT INTO QUOTES VALUES (2411 , "Charles M. Schulz" ,  "humor " ,  "All you need is love. But a little chocolate now and then doesn't hurt. " ); 
INSERT INTO RATING VALUES (2411,5);
INSERT INTO QUOTES VALUES (4802 , "Suzanne Collins" ,  "humor " ,  "Remember, we're madly in love, so it's all right to kiss me anytime you feel like it. " ); 
INSERT INTO RATING VALUES (4802,10);
INSERT INTO QUOTES VALUES (5602 , "Charles Bukowski" ,  "humor " ,  "Some people never go crazy. What truly horrible lives they must lead. " ); 
INSERT INTO RATING VALUES (5602,5);
INSERT INTO QUOTES VALUES (5603 , "Terry Pratchett" ,  "humor " ,  "The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it. " ); 
INSERT INTO RATING VALUES (5603,5);
INSERT INTO QUOTES VALUES (5606 , "Dr. Seuss" ,  "humor " ,  "Think left and think right and think low and think high. Oh, the thinks you can think up if only you try! " ); 
INSERT INTO RATING VALUES (5606,6);
INSERT INTO QUOTES VALUES (5613 , "George Carlin" ,  "humor " ,  "The reason I talk to myself is because I’m the only one whose answers I accept. " ); 
INSERT INTO RATING VALUES (5613,0);
INSERT INTO QUOTES VALUES (5627 , "W.C. Fields" ,  "humor " ,  "I am free of all prejudice. I hate everyone equally.  " ); 
INSERT INTO RATING VALUES (5627,6);
INSERT INTO QUOTES VALUES (6401 , "Jane Austen" ,  "humor " ,  "A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment. " ); 
INSERT INTO RATING VALUES (6401,10);
INSERT INTO QUOTES VALUES (15 , "Marilyn Monroe" ,  "beyourself " ,  "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring. " ); 
INSERT INTO RATING VALUES (15,7);
INSERT INTO QUOTES VALUES (17 , "Albert Einstein" ,  "adulthood " ,  "Try not to become a man of success. Rather become a man of value. " ); 
INSERT INTO RATING VALUES (17,7);
INSERT INTO QUOTES VALUES (18 , "Albert Einstein" ,  "success " ,  "Try not to become a man of success. Rather become a man of value. " ); 
INSERT INTO RATING VALUES (18,9);
INSERT INTO QUOTES VALUES (19 , "Albert Einstein" ,  "VALUEZ " ,  "Try not to become a man of success. Rather become a man of value. " ); 
INSERT INTO RATING VALUES (19,0);
INSERT INTO QUOTES VALUES (21 , "André Gide" ,  "love " ,  "It is better to be hated for what you are than to be loved for what you are not. " ); 
INSERT INTO RATING VALUES (21,1);
INSERT INTO QUOTES VALUES (804 , "Marilyn Monroe" ,  "love " ,  "This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about. " ); 
INSERT INTO RATING VALUES (804,2);
INSERT INTO QUOTES VALUES (810 , "Bob Marley" ,  "love " ,  "You may not be her first, her last, or her only. She loved before she may love again. But if she loves you now, what else matters? She's not perfect—you aren't either, and the two of you may never be perfect together but if she can make you laugh, cause you to think twice, and admit to being human and making mistakes, hold onto her and give her the most you can. She may not be thinking about you every second of the day, but she will give you a part of her that she knows you can break—her heart. So don't hurt her, don't change her, don't analyze and don't expect more than she can give. Smile when she makes you happy, let her know when she makes you mad, and miss her when she's not there. " ); 
INSERT INTO RATING VALUES (810,1);
INSERT INTO QUOTES VALUES (819 , "Elie Wiesel" ,  "love " ,  "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference. " ); 
INSERT INTO RATING VALUES (819,10);
INSERT INTO QUOTES VALUES (825 , "Friedrich Nietzsche" ,  "love " ,  "It is not a lack of love, but a lack of friendship that makes unhappy marriages. " ); 
INSERT INTO RATING VALUES (825,0);
INSERT INTO QUOTES VALUES (1600 , "Pablo Neruda" ,  "love " ,  "I love you without knowing how, or when, or from where. I love you simply, without problems or pride: I love you in this way because I do not know any other way of loving but this, in which there is no I or you, so intimate that your hand upon my chest is my hand, so intimate that when I fall asleep your eyes close. " ); 
INSERT INTO RATING VALUES (1600,9);
INSERT INTO QUOTES VALUES (3209 , "Marilyn Monroe" ,  "love " ,  "If you can make a woman laugh, you can make her do anything. " ); 
INSERT INTO RATING VALUES (3209,6);
INSERT INTO QUOTES VALUES (3212 , "Marilyn Monroe" ,  "love " ,  "The real lover is the man who can thrill you by kissing your forehead or smiling into your eyes or just staring into space. " ); 
INSERT INTO RATING VALUES (3212,0);
INSERT INTO QUOTES VALUES (3217 , "James Baldwin" ,  "love " ,  "Love does not begin and end the way we seem to think it does. Love is a battle, love is a war; love is a growing up. " ); 
INSERT INTO RATING VALUES (3217,6);
INSERT INTO QUOTES VALUES (4001 , "Jane Austen" ,  "love " ,  "There is nothing I would not do for those who are really my friends. I have no notion of loving people by halves, it is not my nature. " ); 
INSERT INTO RATING VALUES (4001,9);
INSERT INTO QUOTES VALUES (4803 , "C.S. Lewis" ,  "love " ,  "To love at all is to be vulnerable. Love anything and your heart will be wrung and possibly broken. If you want to make sure of keeping it intact you must give it to no one, not even an animal. Wrap it carefully round with hobbies and little luxuries; avoid all entanglements. Lock it up safe in the casket or coffin of your selfishness. But in that casket, safe, dark, motionless, airless, it will change. It will not be broken; it will become unbreakable, impenetrable, irredeemable. To love is to be vulnerable. " ); 
INSERT INTO RATING VALUES (4803,2);
INSERT INTO QUOTES VALUES (5601 , "Alfred Tennyson" ,  "love " ,  "If I had a flower for every time I thought of you...I could walk through my garden forever. " ); 
INSERT INTO RATING VALUES (5601,0);
INSERT INTO QUOTES VALUES (6402 , "Jane Austen" ,  "love " ,  "A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment. " ); 
INSERT INTO RATING VALUES (6402,6);
INSERT INTO QUOTES VALUES (7204 , "J.M. Barrie" ,  "love " ,  "To die will be an awfully big adventure. " ); 
INSERT INTO RATING VALUES (7204,3);
INSERT INTO QUOTES VALUES (22 , "Thomas A. Edison" ,  "edison " ,  "I have not failed. I've just found 10,000 ways that won't work. " ); 
INSERT INTO RATING VALUES (22,9);
INSERT INTO QUOTES VALUES (23 , "Thomas A. Edison" ,  "failure " ,  "I have not failed. I've just found 10,000 ways that won't work. " ); 
INSERT INTO RATING VALUES (23,10);
INSERT INTO QUOTES VALUES (25 , "Thomas A. Edison" ,  "paraphrased " ,  "I have not failed. I've just found 10,000 ways that won't work. " ); 
INSERT INTO RATING VALUES (25,8);
INSERT INTO QUOTES VALUES (2406 , "Mother Teresa" ,  "paraphrased " ,  "Not all of us can do great things. But we can do small things with great love. " ); 
INSERT INTO RATING VALUES (2406,7);
INSERT INTO QUOTES VALUES (26 , "Eleanor Roosevelt" ,  "misattributedeleanorroosevelt " ,  "A woman is like a tea bag; you never know how strong it is until it's in hot water. " ); 
INSERT INTO RATING VALUES (26,2);
INSERT INTO QUOTES VALUES (28 , "Steve Martin" ,  "obvious " ,  "A day without sunshine is like, you know, night. " ); 
INSERT INTO RATING VALUES (28,9);
INSERT INTO QUOTES VALUES (29 , "Steve Martin" ,  "simile " ,  "A day without sunshine is like, you know, night. " ); 
INSERT INTO RATING VALUES (29,10);
INSERT INTO QUOTES VALUES (3211 , "Albert Einstein" ,  "simile " ,  "Life is like riding a bicycle. To keep your balance, you must keep moving. " ); 
INSERT INTO RATING VALUES (3211,10);
INSERT INTO QUOTES VALUES (4012 , "Stephenie Meyer" ,  "simile " ,  "He's like a drug for you, Bella. " ); 
INSERT INTO RATING VALUES (4012,6);
INSERT INTO QUOTES VALUES (800 , "Marilyn Monroe" ,  "friends " ,  "This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about. " ); 
INSERT INTO RATING VALUES (800,3);
INSERT INTO QUOTES VALUES (807 , "J.K. Rowling" ,  "friends " ,  "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends. " ); 
INSERT INTO RATING VALUES (807,3);
INSERT INTO QUOTES VALUES (830 , "Mark Twain" ,  "friends " ,  "Good friends, good books, and a sleepy conscience: this is the ideal life. " ); 
INSERT INTO RATING VALUES (830,10);
INSERT INTO QUOTES VALUES (4014 , "Ernest Hemingway" ,  "friends " ,  "There is no friend as loyal as a book. " ); 
INSERT INTO RATING VALUES (4014,10);
INSERT INTO QUOTES VALUES (801 , "Marilyn Monroe" ,  "heartbreak " ,  "This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about. " ); 
INSERT INTO RATING VALUES (801,3);
INSERT INTO QUOTES VALUES (805 , "Marilyn Monroe" ,  "sisters " ,  "This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about. " ); 
INSERT INTO RATING VALUES (805,1);
INSERT INTO QUOTES VALUES (806 , "J.K. Rowling" ,  "courage " ,  "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends. " ); 
INSERT INTO RATING VALUES (806,0);
INSERT INTO QUOTES VALUES (7205 , "E.E. Cummings" ,  "courage " ,  "It takes courage to grow up and become who you really are. " ); 
INSERT INTO RATING VALUES (7205,4);
INSERT INTO QUOTES VALUES (808 , "Albert Einstein" ,  "simplicity " ,  "If you can't explain it to a six year old, you don't understand it yourself. " ); 
INSERT INTO RATING VALUES (808,4);
INSERT INTO QUOTES VALUES (809 , "Albert Einstein" ,  "understand " ,  "If you can't explain it to a six year old, you don't understand it yourself. " ); 
INSERT INTO RATING VALUES (809,10);
INSERT INTO QUOTES VALUES (811 , "Dr. Seuss" ,  "fantasy " ,  "I like nonsense, it wakes up the brain cells. Fantasy is a necessary ingredient in living. " ); 
INSERT INTO RATING VALUES (811,8);
INSERT INTO QUOTES VALUES (813 , "Douglas Adams" ,  "navigation " ,  "I may not have gone where I intended to go, but I think I have ended up where I needed to be. " ); 
INSERT INTO RATING VALUES (813,2);
INSERT INTO QUOTES VALUES (814 , "Elie Wiesel" ,  "activism " ,  "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference. " ); 
INSERT INTO RATING VALUES (814,1);
INSERT INTO QUOTES VALUES (815 , "Elie Wiesel" ,  "apathy " ,  "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference. " ); 
INSERT INTO RATING VALUES (815,3);
INSERT INTO QUOTES VALUES (816 , "Elie Wiesel" ,  "hate " ,  "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference. " ); 
INSERT INTO RATING VALUES (816,9);
INSERT INTO QUOTES VALUES (817 , "Elie Wiesel" ,  "indifference " ,  "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference. " ); 
INSERT INTO RATING VALUES (817,7);
INSERT INTO QUOTES VALUES (820 , "Elie Wiesel" ,  "opposite " ,  "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference. " ); 
INSERT INTO RATING VALUES (820,9);
INSERT INTO QUOTES VALUES (821 , "Elie Wiesel" ,  "philosophy " ,  "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference. " ); 
INSERT INTO RATING VALUES (821,3);
INSERT INTO QUOTES VALUES (5607 , "Dr. Seuss" ,  "philosophy " ,  "Think left and think right and think low and think high. Oh, the thinks you can think up if only you try! " ); 
INSERT INTO RATING VALUES (5607,2);
INSERT INTO QUOTES VALUES (822 , "Friedrich Nietzsche" ,  "friendship " ,  "It is not a lack of love, but a lack of friendship that makes unhappy marriages. " ); 
INSERT INTO RATING VALUES (822,10);
INSERT INTO QUOTES VALUES (831 , "Mark Twain" ,  "friendship " ,  "Good friends, good books, and a sleepy conscience: this is the ideal life. " ); 
INSERT INTO RATING VALUES (831,6);
INSERT INTO QUOTES VALUES (2404 , "Bob Marley" ,  "friendship " ,  "The truth is, everyone is going to hurt you. You just got to find the ones worth suffering for. " ); 
INSERT INTO RATING VALUES (2404,8);
INSERT INTO QUOTES VALUES (4000 , "Jane Austen" ,  "friendship " ,  "There is nothing I would not do for those who are really my friends. I have no notion of loving people by halves, it is not my nature. " ); 
INSERT INTO RATING VALUES (4000,3);
INSERT INTO QUOTES VALUES (5600 , "Alfred Tennyson" ,  "friendship " ,  "If I had a flower for every time I thought of you...I could walk through my garden forever. " ); 
INSERT INTO RATING VALUES (5600,9);
INSERT INTO QUOTES VALUES (823 , "Friedrich Nietzsche" ,  "lackoffriendship " ,  "It is not a lack of love, but a lack of friendship that makes unhappy marriages. " ); 
INSERT INTO RATING VALUES (823,10);
INSERT INTO QUOTES VALUES (824 , "Friedrich Nietzsche" ,  "lackoflove " ,  "It is not a lack of love, but a lack of friendship that makes unhappy marriages. " ); 
INSERT INTO RATING VALUES (824,8);
INSERT INTO QUOTES VALUES (826 , "Friedrich Nietzsche" ,  "marriage " ,  "It is not a lack of love, but a lack of friendship that makes unhappy marriages. " ); 
INSERT INTO RATING VALUES (826,8);
INSERT INTO QUOTES VALUES (827 , "Friedrich Nietzsche" ,  "unhappymarriage " ,  "It is not a lack of love, but a lack of friendship that makes unhappy marriages. " ); 
INSERT INTO RATING VALUES (827,8);
INSERT INTO QUOTES VALUES (829 , "Mark Twain" ,  "contentment " ,  "Good friends, good books, and a sleepy conscience: this is the ideal life. " ); 
INSERT INTO RATING VALUES (829,9);
INSERT INTO QUOTES VALUES (833 , "Allen Saunders" ,  "fate " ,  "Life is what happens to us while we are making other plans. " ); 
INSERT INTO RATING VALUES (833,10);
INSERT INTO QUOTES VALUES (835 , "Allen Saunders" ,  "misattributedjohnlennon " ,  "Life is what happens to us while we are making other plans. " ); 
INSERT INTO RATING VALUES (835,6);
INSERT INTO QUOTES VALUES (836 , "Allen Saunders" ,  "planning " ,  "Life is what happens to us while we are making other plans. " ); 
INSERT INTO RATING VALUES (836,6);
INSERT INTO QUOTES VALUES (837 , "Allen Saunders" ,  "plans " ,  "Life is what happens to us while we are making other plans. " ); 
INSERT INTO RATING VALUES (837,1);
INSERT INTO QUOTES VALUES (1601 , "Pablo Neruda" ,  "poetry " ,  "I love you without knowing how, or when, or from where. I love you simply, without problems or pride: I love you in this way because I do not know any other way of loving but this, in which there is no I or you, so intimate that your hand upon my chest is my hand, so intimate that when I fall asleep your eyes close. " ); 
INSERT INTO RATING VALUES (1601,7);
INSERT INTO QUOTES VALUES (1602 , "Ralph Waldo Emerson" ,  "happiness " ,  "For every minute you are angry you lose sixty seconds of happiness. " ); 
INSERT INTO RATING VALUES (1602,2);
INSERT INTO QUOTES VALUES (1603 , "Mother Teresa" ,  "attributednosource " ,  "If you judge people, you have no time to love them. " ); 
INSERT INTO RATING VALUES (1603,9);
INSERT INTO QUOTES VALUES (3213 , "Marilyn Monroe" ,  "attributednosource " ,  "A wise girl kisses but doesn't love, listens but doesn't believe, and leaves before she is left. " ); 
INSERT INTO RATING VALUES (3213,2);
INSERT INTO QUOTES VALUES (4005 , "Marilyn Monroe" ,  "attributednosource " ,  "I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love. " ); 
INSERT INTO RATING VALUES (4005,8);
INSERT INTO QUOTES VALUES (1605 , "Garrison Keillor" ,  "religion " ,  "Anyone who thinks sitting in church can make you a Christian must also think that sitting in a garage can make you a car. " ); 
INSERT INTO RATING VALUES (1605,3);
INSERT INTO QUOTES VALUES (6421 , "C.S. Lewis" ,  "religion " ,  "I believe in Christianity as I believe that the sun has risen: not only because I see it, but because by it I see everything else. " ); 
INSERT INTO RATING VALUES (6421,0);
INSERT INTO QUOTES VALUES (1607 , "Dr. Seuss" ,  "comedy " ,  "Today you are You, that is truer than true. There is no one alive who is Youer than You. " ); 
INSERT INTO RATING VALUES (1607,4);
INSERT INTO QUOTES VALUES (1609 , "Dr. Seuss" ,  "yourself " ,  "Today you are You, that is truer than true. There is no one alive who is Youer than You. " ); 
INSERT INTO RATING VALUES (1609,3);
INSERT INTO QUOTES VALUES (4019 , "George Bernard Shaw" ,  "yourself " ,  "Life isn't about finding yourself. Life is about creating yourself. " ); 
INSERT INTO RATING VALUES (4019,1);
INSERT INTO QUOTES VALUES (1610 , "Albert Einstein" ,  "children " ,  "If you want your children to be intelligent, read them fairy tales. If you want them to be more intelligent, read them more fairy tales. " ); 
INSERT INTO RATING VALUES (1610,0);
INSERT INTO QUOTES VALUES (7209 , "Madeleine L'Engle" ,  "children " ,  "You have to write the book that wants to be written. And if the book will be too difficult for grown-ups, then you write it for children. " ); 
INSERT INTO RATING VALUES (7209,8);
INSERT INTO QUOTES VALUES (1611 , "Albert Einstein" ,  "fairytales " ,  "If you want your children to be intelligent, read them fairy tales. If you want them to be more intelligent, read them more fairy tales. " ); 
INSERT INTO RATING VALUES (1611,7);
INSERT INTO QUOTES VALUES (6412 , "C.S. Lewis" ,  "fairytales " ,  "Some day you will be old enough to start reading fairy tales again. " ); 
INSERT INTO RATING VALUES (6412,5);
INSERT INTO QUOTES VALUES (1612 , "Albert Einstein" ,  "imagination " ,  "Logic will get you from A to Z; imagination will get you everywhere. " ); 
INSERT INTO RATING VALUES (1612,2);
INSERT INTO QUOTES VALUES (1613 , "Bob Marley" ,  "music " ,  "One good thing about music, when it hits you, you feel no pain. " ); 
INSERT INTO RATING VALUES (1613,4);
INSERT INTO QUOTES VALUES (4006 , "Albert Einstein" ,  "music " ,  "If I were not a physicist, I would probably be a musician. I often think in music. I live my daydreams in music. I see my life in terms of music. " ); 
INSERT INTO RATING VALUES (4006,1);
INSERT INTO QUOTES VALUES (2400 , "Dr. Seuss" ,  "learning " ,  "The more that you read, the more things you will know. The more that you learn, the more places you'll go. " ); 
INSERT INTO RATING VALUES (2400,2);
INSERT INTO QUOTES VALUES (2415 , "Albert Einstein" ,  "learning " ,  "Any fool can know. The point is to understand. " ); 
INSERT INTO RATING VALUES (2415,2);
INSERT INTO QUOTES VALUES (2401 , "Dr. Seuss" ,  "READZing " ,  "The more that you read, the more things you will know. The more that you learn, the more places you'll go. " ); 
INSERT INTO RATING VALUES (2401,4);
INSERT INTO QUOTES VALUES (2413 , "William Nicholson" ,  "READZing " ,  "We read to know we're not alone. " ); 
INSERT INTO RATING VALUES (2413,3);
INSERT INTO QUOTES VALUES (3202 , "George R.R. Martin" ,  "READZing " ,  "A reader lives a thousand lives before he dies, said Jojen. The man who never reads lives only one. " ); 
INSERT INTO RATING VALUES (3202,1);
INSERT INTO QUOTES VALUES (3206 , "C.S. Lewis" ,  "READZing " ,  "You can never get a cup of tea large enough or a book long enough to suit me. " ); 
INSERT INTO RATING VALUES (3206,0);
INSERT INTO QUOTES VALUES (5611 , "J.D. Salinger" ,  "READZing " ,  "What really knocks me out is a book that, when you're all done reading it, you wish the author that wrote it was a terrific friend of yours and you could call him up on the phone whenever you felt like it. That doesn't happen much, though. " ); 
INSERT INTO RATING VALUES (5611,10);
INSERT INTO QUOTES VALUES (5631 , "Mark Twain" ,  "READZing " ,  "′Classic′ - a book which people praise and don't read. " ); 
INSERT INTO RATING VALUES (5631,4);
INSERT INTO QUOTES VALUES (6408 , "Jane Austen" ,  "READZing " ,  "I declare after all there is no enjoyment like reading! How much sooner one tires of any thing than of a book! -- When I have a house of my own, I shall be miserable if I have not an excellent library. " ); 
INSERT INTO RATING VALUES (6408,3);
INSERT INTO QUOTES VALUES (2402 , "Dr. Seuss" ,  "seuss " ,  "The more that you read, the more things you will know. The more that you learn, the more places you'll go. " ); 
INSERT INTO RATING VALUES (2402,2);
INSERT INTO QUOTES VALUES (2403 , "J.K. Rowling" ,  "dumbledore " ,  "Of course it is happening inside your head, Harry, but why on earth should that mean that it is not real? " ); 
INSERT INTO RATING VALUES (2403,6);
INSERT INTO QUOTES VALUES (3216 , "J.K. Rowling" ,  "dumbledore " ,  "It matters not what someone is born, but what they grow to be. " ); 
INSERT INTO RATING VALUES (3216,4);
INSERT INTO QUOTES VALUES (2405 , "Mother Teresa" ,  "misattributedtomotherteresa " ,  "Not all of us can do great things. But we can do small things with great love. " ); 
INSERT INTO RATING VALUES (2405,5);
INSERT INTO QUOTES VALUES (2407 , "J.K. Rowling" ,  "death " ,  "To the well-organized mind, death is but the next great adventure. " ); 
INSERT INTO RATING VALUES (2407,3);
INSERT INTO QUOTES VALUES (6415 , "Mark Twain" ,  "death " ,  "The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time. " ); 
INSERT INTO RATING VALUES (6415,9);
INSERT INTO QUOTES VALUES (7201 , "Jimi Hendrix" ,  "death " ,  "I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to. " ); 
INSERT INTO RATING VALUES (7201,9);
INSERT INTO QUOTES VALUES (2409 , "Charles M. Schulz" ,  "chocolate " ,  "All you need is love. But a little chocolate now and then doesn't hurt. " ); 
INSERT INTO RATING VALUES (2409,1);
INSERT INTO QUOTES VALUES (2410 , "Charles M. Schulz" ,  "food " ,  "All you need is love. But a little chocolate now and then doesn't hurt. " ); 
INSERT INTO RATING VALUES (2410,5);
INSERT INTO QUOTES VALUES (2412 , "William Nicholson" ,  "misattributedtocslewis " ,  "We read to know we're not alone. " ); 
INSERT INTO RATING VALUES (2412,10);
INSERT INTO QUOTES VALUES (2414 , "Albert Einstein" ,  "knowledge " ,  "Any fool can know. The point is to understand. " ); 
INSERT INTO RATING VALUES (2414,1);
INSERT INTO QUOTES VALUES (2416 , "Albert Einstein" ,  "understanding " ,  "Any fool can know. The point is to understand. " ); 
INSERT INTO RATING VALUES (2416,7);
INSERT INTO QUOTES VALUES (2417 , "Albert Einstein" ,  "wisdom " ,  "Any fool can know. The point is to understand. " ); 
INSERT INTO RATING VALUES (2417,8);
INSERT INTO QUOTES VALUES (2419 , "Jorge Luis Borges" ,  "library " ,  "I have always imagined that Paradise will be a kind of library. " ); 
INSERT INTO RATING VALUES (2419,1);
INSERT INTO QUOTES VALUES (6407 , "Jane Austen" ,  "library " ,  "I declare after all there is no enjoyment like reading! How much sooner one tires of any thing than of a book! -- When I have a house of my own, I shall be miserable if I have not an excellent library. " ); 
INSERT INTO RATING VALUES (6407,6);
INSERT INTO QUOTES VALUES (3200 , "George R.R. Martin" ,  "READZ " ,  "A reader lives a thousand lives before he dies, said Jojen. The man who never reads lives only one. " ); 
INSERT INTO RATING VALUES (3200,10);
INSERT INTO QUOTES VALUES (3201 , "George R.R. Martin" ,  "READZers " ,  "A reader lives a thousand lives before he dies, said Jojen. The man who never reads lives only one. " ); 
INSERT INTO RATING VALUES (3201,8);
INSERT INTO QUOTES VALUES (3203 , "George R.R. Martin" ,  "READZingbooks " ,  "A reader lives a thousand lives before he dies, said Jojen. The man who never reads lives only one. " ); 
INSERT INTO RATING VALUES (3203,3);
INSERT INTO QUOTES VALUES (3207 , "C.S. Lewis" ,  "tea " ,  "You can never get a cup of tea large enough or a book long enough to suit me. " ); 
INSERT INTO RATING VALUES (3207,6);
INSERT INTO QUOTES VALUES (3208 , "Marilyn Monroe" ,  "girls " ,  "If you can make a woman laugh, you can make her do anything. " ); 
INSERT INTO RATING VALUES (3208,8);
INSERT INTO QUOTES VALUES (3214 , "Martin Luther King Jr." ,  "hope " ,  "Only in the darkness can you see the stars. " ); 
INSERT INTO RATING VALUES (3214,3);
INSERT INTO QUOTES VALUES (5624 , "John Lennon" ,  "hope " ,  "You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one. " ); 
INSERT INTO RATING VALUES (5624,9);
INSERT INTO QUOTES VALUES (4002 , "Eleanor Roosevelt" ,  "attributed " ,  "Do one thing every day that scares you. " ); 
INSERT INTO RATING VALUES (4002,1);
INSERT INTO QUOTES VALUES (4003 , "Eleanor Roosevelt" ,  "fear " ,  "Do one thing every day that scares you. " ); 
INSERT INTO RATING VALUES (4003,1);
INSERT INTO QUOTES VALUES (4004 , "Eleanor Roosevelt" ,  "inspiration " ,  "Do one thing every day that scares you. " ); 
INSERT INTO RATING VALUES (4004,1);
INSERT INTO QUOTES VALUES (4008 , "Haruki Murakami" ,  "thought " ,  "If you only read the books that everyone else is reading, you can only think what everyone else is thinking. " ); 
INSERT INTO RATING VALUES (4008,8);
INSERT INTO QUOTES VALUES (4009 , "Alexandre Dumas fils" ,  "misattributedtoeinstein " ,  "The difference between genius and stupidity is: genius has its limits. " ); 
INSERT INTO RATING VALUES (4009,10);
INSERT INTO QUOTES VALUES (4010 , "Stephenie Meyer" ,  "drug " ,  "He's like a drug for you, Bella. " ); 
INSERT INTO RATING VALUES (4010,9);
INSERT INTO QUOTES VALUES (4011 , "Stephenie Meyer" ,  "romance " ,  "He's like a drug for you, Bella. " ); 
INSERT INTO RATING VALUES (4011,0);
INSERT INTO QUOTES VALUES (4015 , "Ernest Hemingway" ,  "novelistquotes " ,  "There is no friend as loyal as a book. " ); 
INSERT INTO RATING VALUES (4015,4);
INSERT INTO QUOTES VALUES (4800 , "Charles Bukowski" ,  "alcohol " ,  "That's the problem with drinking, I thought, as I poured myself a drink. If something bad happens you drink in an attempt to forget; if something good happens you drink in order to celebrate; and if nothing happens you drink to make something happen. " ); 
INSERT INTO RATING VALUES (4800,6);
INSERT INTO QUOTES VALUES (4801 , "Suzanne Collins" ,  "thehungergames " ,  "You don’t forget the face of the person who was your last hope. " ); 
INSERT INTO RATING VALUES (4801,9);
INSERT INTO QUOTES VALUES (4804 , "J.R.R. Tolkien" ,  "bilbo " ,  "Not all those who wander are lost. " ); 
INSERT INTO RATING VALUES (4804,6);
INSERT INTO QUOTES VALUES (4805 , "J.R.R. Tolkien" ,  "journey " ,  "Not all those who wander are lost. " ); 
INSERT INTO RATING VALUES (4805,2);
INSERT INTO QUOTES VALUES (4806 , "J.R.R. Tolkien" ,  "lost " ,  "Not all those who wander are lost. " ); 
INSERT INTO RATING VALUES (4806,2);
INSERT INTO QUOTES VALUES (4807 , "J.R.R. Tolkien" ,  "quest " ,  "Not all those who wander are lost. " ); 
INSERT INTO RATING VALUES (4807,7);
INSERT INTO QUOTES VALUES (4808 , "J.R.R. Tolkien" ,  "travel " ,  "Not all those who wander are lost. " ); 
INSERT INTO RATING VALUES (4808,8);
INSERT INTO QUOTES VALUES (4809 , "J.R.R. Tolkien" ,  "wander " ,  "Not all those who wander are lost. " ); 
INSERT INTO RATING VALUES (4809,2);
INSERT INTO QUOTES VALUES (4810 , "J.K. Rowling" ,  "livedeathlove " ,  "Do not pity the dead, Harry. Pity the living, and, above all those who live without love. " ); 
INSERT INTO RATING VALUES (4810,5);
INSERT INTO QUOTES VALUES (4811 , "Ernest Hemingway" ,  "good " ,  "There is nothing to writing. All you do is sit down at a typewriter and bleed. " ); 
INSERT INTO RATING VALUES (4811,4);
INSERT INTO QUOTES VALUES (4812 , "Ernest Hemingway" ,  "writing " ,  "There is nothing to writing. All you do is sit down at a typewriter and bleed. " ); 
INSERT INTO RATING VALUES (4812,9);
INSERT INTO QUOTES VALUES (5612 , "J.D. Salinger" ,  "writing " ,  "What really knocks me out is a book that, when you're all done reading it, you wish the author that wrote it was a terrific friend of yours and you could call him up on the phone whenever you felt like it. That doesn't happen much, though. " ); 
INSERT INTO RATING VALUES (5612,8);
INSERT INTO QUOTES VALUES (7214 , "Madeleine L'Engle" ,  "writing " ,  "You have to write the book that wants to be written. And if the book will be too difficult for grown-ups, then you write it for children. " ); 
INSERT INTO RATING VALUES (7214,6);
INSERT INTO QUOTES VALUES (4814 , "Ralph Waldo Emerson" ,  "regrets " ,  "Finish each day and be done with it. You have done what you could. Some blunders and absurdities no doubt crept in; forget them as soon as you can. Tomorrow is a new day. You shall begin it serenely and with too high a spirit to be encumbered with your old nonsense. " ); 
INSERT INTO RATING VALUES (4814,4);
INSERT INTO QUOTES VALUES (4815 , "Mark Twain" ,  "education " ,  "I have never let my schooling interfere with my education. " ); 
INSERT INTO RATING VALUES (4815,6);
INSERT INTO QUOTES VALUES (4816 , "Dr. Seuss" ,  "troubles " ,  "I have heard there are troubles of more than one kind. Some come from ahead and some come from behind. But I've bought a big bat. I'm all ready you see. Now my troubles are going to have troubles with me! " ); 
INSERT INTO RATING VALUES (4816,5);
INSERT INTO QUOTES VALUES (5604 , "Terry Pratchett" ,  "openmind " ,  "The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it. " ); 
INSERT INTO RATING VALUES (5604,1);
INSERT INTO QUOTES VALUES (5608 , "J.D. Salinger" ,  "authors " ,  "What really knocks me out is a book that, when you're all done reading it, you wish the author that wrote it was a terrific friend of yours and you could call him up on the phone whenever you felt like it. That doesn't happen much, though. " ); 
INSERT INTO RATING VALUES (5608,0);
INSERT INTO QUOTES VALUES (5610 , "J.D. Salinger" ,  "literature " ,  "What really knocks me out is a book that, when you're all done reading it, you wish the author that wrote it was a terrific friend of yours and you could call him up on the phone whenever you felt like it. That doesn't happen much, though. " ); 
INSERT INTO RATING VALUES (5610,7);
INSERT INTO QUOTES VALUES (5614 , "George Carlin" ,  "insanity " ,  "The reason I talk to myself is because I’m the only one whose answers I accept. " ); 
INSERT INTO RATING VALUES (5614,1);
INSERT INTO QUOTES VALUES (5615 , "George Carlin" ,  "lies " ,  "The reason I talk to myself is because I’m the only one whose answers I accept. " ); 
INSERT INTO RATING VALUES (5615,4);
INSERT INTO QUOTES VALUES (5616 , "George Carlin" ,  "lying " ,  "The reason I talk to myself is because I’m the only one whose answers I accept. " ); 
INSERT INTO RATING VALUES (5616,0);
INSERT INTO QUOTES VALUES (5617 , "George Carlin" ,  "selfindulgence " ,  "The reason I talk to myself is because I’m the only one whose answers I accept. " ); 
INSERT INTO RATING VALUES (5617,3);
INSERT INTO QUOTES VALUES (5618 , "George Carlin" ,  "truth " ,  "The reason I talk to myself is because I’m the only one whose answers I accept. " ); 
INSERT INTO RATING VALUES (5618,3);
INSERT INTO QUOTES VALUES (6418 , "Mark Twain" ,  "truth " ,  "A lie can travel half way around the world while the truth is putting on its shoes. " ); 
INSERT INTO RATING VALUES (6418,5);
INSERT INTO QUOTES VALUES (7200 , "J.K. Rowling" ,  "truth " ,  "The truth." Dumbledore sighed. "It is a beautiful and terrible thing, and should therefore be treated with great caution. " ); 
INSERT INTO RATING VALUES (7200,3);
INSERT INTO QUOTES VALUES (7215 , "Mark Twain" ,  "truth " ,  "Never tell the truth to people who are not worthy of it. " ); 
INSERT INTO RATING VALUES (7215,8);
INSERT INTO QUOTES VALUES (5619 , "John Lennon" ,  "beatles " ,  "You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one. " ); 
INSERT INTO RATING VALUES (5619,5);
INSERT INTO QUOTES VALUES (5620 , "John Lennon" ,  "connection " ,  "You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one. " ); 
INSERT INTO RATING VALUES (5620,8);
INSERT INTO QUOTES VALUES (5621 , "John Lennon" ,  "dreamers " ,  "You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one. " ); 
INSERT INTO RATING VALUES (5621,8);
INSERT INTO QUOTES VALUES (5622 , "John Lennon" ,  "dreaming " ,  "You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one. " ); 
INSERT INTO RATING VALUES (5622,1);
INSERT INTO QUOTES VALUES (5623 , "John Lennon" ,  "dreams " ,  "You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one. " ); 
INSERT INTO RATING VALUES (5623,9);
INSERT INTO QUOTES VALUES (5626 , "John Lennon" ,  "peace " ,  "You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one. " ); 
INSERT INTO RATING VALUES (5626,2);
INSERT INTO QUOTES VALUES (5628 , "W.C. Fields" ,  "sinister " ,  "I am free of all prejudice. I hate everyone equally.  " ); 
INSERT INTO RATING VALUES (5628,0);
INSERT INTO QUOTES VALUES (6400 , "Albert Einstein" ,  "mistakes " ,  "Anyone who has never made a mistake has never tried anything new. " ); 
INSERT INTO RATING VALUES (6400,9);
INSERT INTO QUOTES VALUES (6403 , "Jane Austen" ,  "romantic " ,  "A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment. " ); 
INSERT INTO RATING VALUES (6403,3);
INSERT INTO QUOTES VALUES (6404 , "Jane Austen" ,  "women " ,  "A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment. " ); 
INSERT INTO RATING VALUES (6404,0);
INSERT INTO QUOTES VALUES (6405 , "J.K. Rowling" ,  "integrity " ,  "Remember, if the time should come when you have to make a choice between what is right and what is easy, remember what happened to a boy who was good, and kind, and brave, because he strayed across the path of Lord Voldemort. Remember Cedric Diggory. " ); 
INSERT INTO RATING VALUES (6405,4);
INSERT INTO QUOTES VALUES (6409 , "Jane Austen" ,  "elizabethbennet " ,  "There are few people whom I really love, and still fewer of whom I think well. The more I see of the world, the more am I dissatisfied with it; and every day confirms my belief of the inconsistency of all human characters, and of the little dependence that can be placed on the appearance of merit or sense. " ); 
INSERT INTO RATING VALUES (6409,2);
INSERT INTO QUOTES VALUES (6410 , "Jane Austen" ,  "janeausten " ,  "There are few people whom I really love, and still fewer of whom I think well. The more I see of the world, the more am I dissatisfied with it; and every day confirms my belief of the inconsistency of all human characters, and of the little dependence that can be placed on the appearance of merit or sense. " ); 
INSERT INTO RATING VALUES (6410,1);
INSERT INTO QUOTES VALUES (6411 , "C.S. Lewis" ,  "age " ,  "Some day you will be old enough to start reading fairy tales again. " ); 
INSERT INTO RATING VALUES (6411,4);
INSERT INTO QUOTES VALUES (6413 , "C.S. Lewis" ,  "growingup " ,  "Some day you will be old enough to start reading fairy tales again. " ); 
INSERT INTO RATING VALUES (6413,5);
INSERT INTO QUOTES VALUES (6414 , "C.S. Lewis" ,  "god " ,  "We are not necessarily doubting that God will do the best for us; we are wondering how painful the best will turn out to be. " ); 
INSERT INTO RATING VALUES (6414,1);
INSERT INTO QUOTES VALUES (6417 , "Mark Twain" ,  "misattributedmarktwain " ,  "A lie can travel half way around the world while the truth is putting on its shoes. " ); 
INSERT INTO RATING VALUES (6417,1);
INSERT INTO QUOTES VALUES (6419 , "C.S. Lewis" ,  "christianity " ,  "I believe in Christianity as I believe that the sun has risen: not only because I see it, but because by it I see everything else. " ); 
INSERT INTO RATING VALUES (6419,9);
INSERT INTO QUOTES VALUES (6420 , "C.S. Lewis" ,  "faith " ,  "I believe in Christianity as I believe that the sun has risen: not only because I see it, but because by it I see everything else. " ); 
INSERT INTO RATING VALUES (6420,2);
INSERT INTO QUOTES VALUES (6422 , "C.S. Lewis" ,  "sun " ,  "I believe in Christianity as I believe that the sun has risen: not only because I see it, but because by it I see everything else. " ); 
INSERT INTO RATING VALUES (6422,7);
INSERT INTO QUOTES VALUES (7203 , "J.M. Barrie" ,  "adventure " ,  "To die will be an awfully big adventure. " ); 
INSERT INTO RATING VALUES (7203,8);
INSERT INTO QUOTES VALUES (7207 , "Harper Lee" ,  "betterlifeempathy " ,  "You never really understand a person until you consider things from his point of view... Until you climb inside of his skin and walk around in it. " ); 
INSERT INTO RATING VALUES (7207,6);
INSERT INTO QUOTES VALUES (7210 , "Madeleine L'Engle" ,  "difficult " ,  "You have to write the book that wants to be written. And if the book will be too difficult for grown-ups, then you write it for children. " ); 
INSERT INTO RATING VALUES (7210,2);
INSERT INTO QUOTES VALUES (7211 , "Madeleine L'Engle" ,  "grownups " ,  "You have to write the book that wants to be written. And if the book will be too difficult for grown-ups, then you write it for children. " ); 
INSERT INTO RATING VALUES (7211,6);
INSERT INTO QUOTES VALUES (7212 , "Madeleine L'Engle" ,  "write " ,  "You have to write the book that wants to be written. And if the book will be too difficult for grown-ups, then you write it for children. " ); 
INSERT INTO RATING VALUES (7212,2);
INSERT INTO QUOTES VALUES (7213 , "Madeleine L'Engle" ,  "writers " ,  "You have to write the book that wants to be written. And if the book will be too difficult for grown-ups, then you write it for children. " ); 
INSERT INTO RATING VALUES (7213,5);
INSERT INTO QUOTES VALUES (7218 , "George R.R. Martin" ,  "mind " ,  "... a mind needs books as a sword needs a whetstone, if it is to keep its edge. " ); 
INSERT INTO RATING VALUES (7218,6);
